# Generated by Django 5.1 on 2024-09-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("heading", models.CharField(help_text="Введите заголовок", max_length=200, verbose_name="Заголовок")),
                (
                    "content",
                    models.TextField(blank=True, help_text="Введите содержимое", null=True, verbose_name="Содержимое"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение",
                        null=True,
                        upload_to="blog/images/",
                        verbose_name="Превью",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("is_publication", models.BooleanField(blank=True, default=False)),
                ("view_counter", models.IntegerField(blank=True, default=0, verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "db_table": "blog_entry",
                "ordering": ["heading"],
            },
        ),
    ]
